# Generated by Django 5.0.4 on 2024-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False)),
                ('question_answer', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
